### ISSUE TITLE
Context Models

### ISSUE THREAD

**Issue by iek** [zhixingfeng/iGDA#1]
For detecting minor SNVs, what are the differences between the different context models? There seem to be several ONT models, so I wasn't sure which one to select.

**Comment by zhixingfeng** [comment]
Hi iek,
Thank you for your question. The different models are used for different preprocessing methods. If your data is preprocessed by discarding reads with average QV < x and masking bases with QV < y by "N", use the model named "ont_context_effect_read_qv_x_base_qv_y". "qv_0" means no masking.  The "sam_maskqv" command released with iGDA can do the low QV base masking (should be available if you install iGDA using conda), but you could also use any in-house or third-party tools. Many QC tools dealing with FASTQ files can do low average QV reads filtering. Feel free to let me know if you have any other questions.

**Comment by iek** [comment]
Thank you so much! That's very helpful.

**Comment by aretchless** [comment]
Hello @zhixingfeng  -- thanks for providing this information. For what it's worth, I think it would help to add this information to the main documentation (either on IGDA on the context model repository). I did not understand how I was supposed to include the context models on the command line until I read this.

**Comment by zhixingfeng** [comment]
Hi @aretchless, thank you very much for suggestions. Have updated README.md of iGDA. Your feedback is highly very valuable for improving iGDA.
