### ISSUE TITLE
Preprocessing not clear enough 

### ISSUE THREAD

**Issue by gchevignon** [zhixingfeng/iGDA#4]
Hello,

First we need to  "Convert lower case letters to upper case in reference fasta" with  fasta2upper infasta outfasta
Second we need to "Convert wildcard letters to N in reference fasta" with fastaclean fastafile outfafile
Third we need to "Realign reads aligned to the negative strand" with igda_align_ont infile(bam or sam file) reffile outfile nthread

Here there is something I don't understand ....
The output of the previous step is a cleaned fastq file but you ask a bam or sam file as input file for the mapping step ....
The infile is fastq not bam or sam right ?
The output of the mapping is sam file right ?

Best

**Comment by zhixingfeng** [comment]
fasta2upper and fastaclean are dealing with reference sequence file, which is in FASTA format. 

igda_align_pb and igda_align_ont realign the aligned sequencing reads file, which is in BAM format.

**Comment by gchevignon** [comment]
Yes I understand that but I don't understand why we have to preprocess the reads while no reads are needed in any of the following command...

**Comment by zhixingfeng** [comment]
The inputs of the whole pipeline, including the preprocessing and the detection and phasing analysis, are a BAM file, which is the aligned reads and a FASTA file, which is the reference genome. 

First, you should run "fasta2upper" and "fasta2clean" for the FASTA file (reference genome) if it contains lower case letter or wildcard other than N. 

Then, you realign the reads, which is in BAM file to the "preprocessed" reference genome (FASTA format) using "igda_align_pb infile(bam or sam file) reffile outfile nthread", where "infile" is the reads, reffile is the preprocessed FASTA file. You do need "reads" in this command, and you also need the preprocessed reads in the following commands to detect and phase SNVs. For example, for detecting SNVs,

``` 
igda_pipe_detect -m pb bamfile reffile contextmodel outdir
```
where `bamfile` is the preprocessed reads, and reffile is the preprocessed reference genome.

**Comment by gchevignon** [comment]
OK my bad ... I missreading the " in reference fasta" , this is why I thought it was the reads we have to process ...
Sorry for that !
An thanks for your time
Best

**Comment by zhixingfeng** [comment]
No problem.
