### ISSUE TITLE
minimap2 not found

### ISSUE THREAD

**Issue by aretchless** [zhixingfeng/iGDA#6]
Hello. I'm very excited to try iGDA, but am not able to run the 'idga_align_ont' step. I installed iGDA using a fresh conda environment as described in the GitHub page:
`conda install -c bioconda -c conda-forge -c zhixingfeng igda`

When I run 'igda_align_ont' I receive the error message "/scicomp/home-pure/ymw8/Software/miniconda3/envs/igda/bin/igda_align_ont: line 24: minimap2: command not found".

I do have several 'minimap2...' executables in the conda environment (such as "minimap2_nanopore"), but none are simply "minimap2".

Please advise. The full error message is below. Thanks -- Adam.

```
(igda) me> igda_align_ont barcode45.trim.primerclipped.bam iGDA/WuCoV_MN908947_clean.fasta iGDA/barcode45.igda 4
infile=barcode45.trim.primerclipped.bam
reffile=iGDA/WuCoV_MN908947_clean.fasta
outfile=iGDA/barcode45.igda
nthread=4
get forward sequences from sam/bam
run minimap2
~/Software/miniconda3/envs/igda/bin/igda_align_ont: line 24: minimap2: command not found
filter realigned sam
[main_samview] fail to read the header from "iGDA/barcode45.igda.realign.sam".

```

**Comment by aretchless** [comment]
I fixed it with 'conda install minimap2'

**Comment by zhixingfeng** [comment]
Hi Adam,
Thank you so much for pointing this out! Tested on several different machines but didn't find this problem since minimap2 was preinstalled in all these machines. Will update the conda package to add minimap2 as a dependence. 

Best

Zhixing
